spring:
  application:
    name: ${SPRING_APP_NAME:api-gateway}
    profiles:
      active: prod
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: GET, POST, PUT, DELETE, OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
            maxAge: 3600
      loadbalancer:
        retry:
          enabled: true
          max-attempts: 3
          backoff:
            enabled: true
            delay: 1000ms
            max-delay: 5000ms
            multiplier: 1.5
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      response-timeout: 5000ms
      routes:
        - id: eazybank-service
          uri: lb://eazybank-service
          predicates:
            - Path=/eazybank/**
          filters:
            - StripPrefix=1
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1
      
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default: http://localhost:8761/eureka

server:
  port: 8765
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
      timeout: 2m

logging:
  level:
      root: ${LOG_LEVEL_ROOT:INFO}
      com.eazybank: ${LOG_LEVEL_COM_EAZYBANK:DEBUG}
      org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:TRACE}
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/eazybank/eazybank_prod.%d{yyyy-MM-dd}.%i.log
      max-history: 30
      total-size-cap: 1GB
      max-file-size: 10MB
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  file:
    name: /var/log/eazybank/eazybank_prod.log